import type { Category, Coupon, Product } from "./shop-types";

export const SEED_CATEGORIES: Category[] = [
  {
    id: "raw",
    name: "محصولات چوبی خام",
    icon: "🪵",
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=300&h=200&fit=crop",
  },
  {
    id: "furniture",
    name: "مبلمان چوبی",
    icon: "🪑",
    image: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=300&h=200&fit=crop",
  },
  {
    id: "decorative",
    name: "دکوری و تزئینی",
    icon: "🎨",
    image: "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=300&h=200&fit=crop",
  },
  {
    id: "tools",
    name: "ابزار نجاری",
    icon: "🔨",
    image: "https://images.unsplash.com/photo-1504148455328-c376907d081c?w=300&h=200&fit=crop",
  },
  {
    id: "paint",
    name: "رنگ و پوشش",
    icon: "🖌️",
    image: "https://images.unsplash.com/photo-1589939705384-5185137a7f0f?w=300&h=200&fit=crop",
  },
  {
    id: "boards",
    name: "انواع تخته",
    icon: "📦",
    image: "https://images.unsplash.com/photo-1563453392212-326f5e854473?w=300&h=200&fit=crop",
  },
  {
    id: "calligraphy",
    name: "حروف کالیگرافی",
    icon: "✍️",
    image: "/images/calligraphy/calligraphy-5.jpg",
  },
];

const RAW_SEED_PRODUCTS = [
  {
    id: 1,
    name: "جاقلمی چوبی خام دو خانه دالبری",
    price: 85000,
    originalPrice: 110000,
    image: "https://images.unsplash.com/photo-1611532736597-de2d4265fba3?w=400&h=400&fit=crop",
    category: "محصولات چوبی خام",
    categoryId: "raw",
    rating: 0,
    reviewCount: 0,
    isNew: false,
    discount: 22,
    stock: 18,
    lowStockThreshold: 5,
    description: "جاقلمی چوبی خام با دو خانه دالبری، مناسب میز کار و هدیه.",
    active: true,
  },
  {
    id: 2,
    name: "قاب عکس چوبی روستیک سایز A4",
    price: 120000,
    originalPrice: 150000,
    image: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=400&h=400&fit=crop",
    category: "دکوری و تزئینی",
    categoryId: "decorative",
    rating: 0,
    reviewCount: 0,
    isNew: true,
    stock: 4,
    lowStockThreshold: 5,
    description: "قاب عکس چوبی با بافت روستیک، سایز A4 برای عکس‌های خانوادگی.",
    active: true,
  },
  {
    id: 3,
    name: "جعبه چوبی هدیه با درب کشویی",
    price: 95000,
    image: "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=400&h=400&fit=crop",
    category: "محصولات چوبی خام",
    categoryId: "raw",
    rating: 0,
    reviewCount: 0,
    stock: 25,
    lowStockThreshold: 5,
    description: "جعبه هدیه چوبی با درب کشویی، مناسب بسته‌بندی ویژه.",
    active: true,
  },
  {
    id: 4,
    name: "کتاب‌خانه دیواری چوب طبیعی",
    price: 1850000,
    originalPrice: 2200000,
    image: "https://images.unsplash.com/photo-1524758631624-e2822e304c36?w=400&h=400&fit=crop",
    category: "مبلمان چوبی",
    categoryId: "furniture",
    rating: 0,
    reviewCount: 0,
    discount: 15,
    stock: 3,
    lowStockThreshold: 5,
    description: "کتاب‌خانه دیواری از چوب طبیعی، طراحی مینیمال و مقاوم.",
    active: true,
  },
  {
    id: 5,
    name: "ست ابزار نجاری حرفه‌ای ۱۲ عددی",
    price: 380000,
    originalPrice: 450000,
    image: "https://images.unsplash.com/photo-1504148455328-c376907d081c?w=400&h=400&fit=crop",
    category: "ابزار نجاری",
    categoryId: "tools",
    rating: 0,
    reviewCount: 0,
    discount: 15,
    stock: 32,
    lowStockThreshold: 5,
    description: "ست ۱۲ عددی ابزار نجاری حرفه‌ای برای کارگاه و خانه.",
    active: true,
  },
  {
    id: 6,
    name: "میز کنسول چوبی آنتیک",
    price: 2400000,
    image: "https://images.unsplash.com/photo-1549497538-303791108f95?w=400&h=400&fit=crop",
    category: "مبلمان چوبی",
    categoryId: "furniture",
    rating: 0,
    reviewCount: 0,
    isNew: true,
    stock: 5,
    lowStockThreshold: 5,
    description: "میز کنسول چوبی با ظاهر آنتیک، مناسب ورودی و پذیرایی.",
    active: true,
  },
  {
    id: 7,
    name: "رنگ وود استین ماهون ۱ لیتری",
    price: 145000,
    originalPrice: 175000,
    image: "https://images.unsplash.com/photo-1589939705384-5185137a7f0f?w=400&h=400&fit=crop",
    category: "رنگ و پوشش",
    categoryId: "paint",
    rating: 0,
    reviewCount: 0,
    discount: 17,
    stock: 40,
    lowStockThreshold: 5,
    description: "رنگ وود استین ماهون یک لیتری برای پوشش چوب طبیعی.",
    active: true,
  },
  {
    id: 8,
    name: "تابلو دیواری برش لیزر چوب گردو",
    price: 320000,
    image: "https://images.unsplash.com/photo-1612528443702-f6741f70a049?w=400&h=400&fit=crop",
    category: "دکوری و تزئینی",
    categoryId: "decorative",
    rating: 0,
    reviewCount: 0,
    isNew: true,
    stock: 12,
    lowStockThreshold: 5,
    description: "تابلو دیواری برش لیزر از چوب گردو با طرح ظریف.",
    active: true,
  },
  {
    id: 9,
    name: "حروف کالیگرافی چوبی مدل عشق",
    price: 210000,
    originalPrice: 250000,
    image: "/images/calligraphy/calligraphy-1.jpg",
    category: "حروف کالیگرافی",
    categoryId: "calligraphy",
    rating: 0,
    reviewCount: 0,
    isNew: true,
    stock: 22,
    lowStockThreshold: 5,
    description: "حروف کالیگرافی چوبی مدل عشق، مناسب دکوراسیون دیوار.",
    active: true,
  },
  {
    id: 10,
    name: "حروف کالیگرافی آینه‌ای مدل امید",
    price: 185000,
    image: "/images/calligraphy/calligraphy-2.jpg",
    category: "حروف کالیگرافی",
    categoryId: "calligraphy",
    rating: 0,
    reviewCount: 0,
    stock: 15,
    lowStockThreshold: 5,
    description: "حروف کالیگرافی آینه‌ای مدل امید با جلوه لوکس.",
    active: true,
  },
  {
    id: 11,
    name: "تابلو حروف کالیگرافی دیواری مدل زندگی",
    price: 340000,
    originalPrice: 390000,
    image: "/images/calligraphy/calligraphy-4.jpg",
    category: "حروف کالیگرافی",
    categoryId: "calligraphy",
    rating: 0,
    reviewCount: 0,
    discount: 13,
    stock: 8,
    lowStockThreshold: 5,
    description: "تابلو حروف کالیگرافی دیواری مدل زندگی، دست‌ساز و باکیفیت.",
    active: true,
  },
];

export const SEED_PRODUCTS: Product[] = RAW_SEED_PRODUCTS.map((product) => {
  const gallery =
    product.categoryId === "calligraphy"
      ? [
          product.image,
          "/images/calligraphy/calligraphy-1.jpg",
          "/images/calligraphy/calligraphy-2.jpg",
          "/images/calligraphy/calligraphy-5.jpg",
        ].filter((src, index, arr) => arr.indexOf(src) === index)
      : [product.image];

  return {
    ...product,
    images: gallery,
    image: gallery[0],
  };
});

export const SEED_COUPONS: Coupon[] = [
  {
    id: "coupon-prisma10",
    code: "PRISMA10",
    type: "percent",
    value: 10,
    active: true,
    minOrder: 0,
  },
  {
    id: "coupon-wood20",
    code: "WOOD20",
    type: "percent",
    value: 20,
    active: true,
    minOrder: 500000,
  },
  {
    id: "coupon-fixed50",
    code: "FIXED50",
    type: "fixed",
    value: 50000,
    active: true,
    minOrder: 300000,
  },
];
